[workarea]
restrict = ["googlemock/include", "googlemock/src", "googletest/include", "googletest/src"]
[database]
db = "dextool_mutate.sqlite3"
[compiler]
extra_flags = [ "-D_POSIX_PATH_MAX=1024" ]
[compile_commands]
search_paths = ["./build/compile_commands.json"]
[mutant_test]
test_cmd = "test.sh"
# test_cmd_timeout = 7000
build_cmd = "build.sh"
analyze_using_builtin = ["gtest", "ctest"]
