[workarea]
restrict = ["googlemock/include", "googlemock/src", "googletest/include", "googletest/src"]
[analyze]
exclude = ["googlemock/test", "googletest/test"]
[database]
db = "dextool_mutate.sqlite3"
[compiler]
extra_flags = [ "-D_POSIX_PATH_MAX=1024" ]
[compile_commands]
search_paths = ["./build/compile_commands.json"]
filter = ["-c", "-o", "-m", "-nodevicelib", "-Waddr-space-convert", "-non-static", "-Bstatic", "-Bdynamic", "-Xbind-lazy", "-Xbind-now", "-f", "-static", "-shared", "-rdynamic", "-s", "-l", "-L", "-z", "-u", "-T", "-Xlinker", "-l", "-MT", "-MF", "-MD", "-MQ", "-MMD", "-MP", "-MG", "-E", "-cc1", "-S", "-M", "-MM", "-###", "-Werror", "-Wunused-private-field"]
[mutant_test]
test_cmd = [["build/googlemock/shared_gmock_test_"], ["build/googlemock/gmock_stress_test"], ["build/googlemock/gmock-internal-utils_test"], ["build/googlemock/gmock-more-actions_test"], ["build/googlemock/gmock-cardinalities_test"], ["build/googlemock/gmock-generated-actions_test"], ["build/googlemock/gmock-function-mocker_test"], ["build/googlemock/gmock-nice-strict_test"], ["build/googlemock/gmock-port_test"], ["build/googlemock/gmock_ex_test"], ["build/googlemock/gmock_test"], ["build/googlemock/gmock_link_test"], ["build/googlemock/gmock-actions_test"], ["build/googlemock/gmock-generated-matchers_test"], ["build/googlemock/gmock-more-actions_no_exception_test"], ["build/googlemock/gmock_no_rtti_test"], ["build/googlemock/gmock-spec-builders_test"], ["build/googlemock/gmock-matchers_test"], ["build/googletest/googletest-catch-exceptions-no-ex-test_"], ["build/googletest/googletest-throw-on-failure-test_"], ["build/googletest/gtest_premature_exit_test"], ["build/googletest/gtest_environment_test"], ["build/googletest/googletest-port-test"], ["build/googletest/googletest-listener-test"], ["build/googletest/gtest_no_test_unittest"], ["build/googletest/gtest-typed-test_test"], ["build/googletest/googletest-filepath-test"], ["build/googletest/googletest-message-test"], ["build/googletest/googletest-options-test"], ["build/googletest/gtest_xml_outfile2_test_"], ["build/googletest/gtest_main_unittest"], ["build/googletest/gtest_throw_on_failure_ex_test"], ["build/googletest/gtest-death-test_ex_nocatch_test"], ["build/googletest/googletest-death-test-test"], ["build/googletest/gtest-death-test_ex_catch_test"], ["build/googletest/gtest_skip_test"], ["build/googletest/gtest_no_rtti_unittest"], ["build/googletest/googletest-shuffle-test_"], ["build/googletest/gtest_skip_in_environment_setup_test"], ["build/googletest/gtest_repeat_test"], ["build/googletest/gtest-unittest-api_test"], ["build/googletest/googletest-uninitialized-test_"], ["build/googletest/gtest_stress_test"], ["build/googletest/gtest_xml_outfile1_test_"], ["build/googletest/googletest-param-test-test"], ["build/googletest/googletest-list-tests-unittest_"], ["build/googletest/gtest_sole_header_test"], ["build/googletest/googletest-test-part-test"], ["build/googletest/gtest_prod_test"], ["build/googletest/gtest_pred_impl_unittest"], ["build/googletest/googletest-printers-test"], ["build/googletest/gtest_unittest"]]
# failing [["build/googlemock/gmock_output_test_"], ["build/googlemock/gmock_leak_test_"], ["build/googletest/gtest_xml_output_unittest_"], ["build/googletest/googletest-color-test_"], ["build/googletest/googletest-break-on-failure-unittest_"], ["build/googletest/googletest-filter-unittest_"], ["build/googletest/googletest-catch-exceptions-ex-test_"], ["build/googletest/googletest-output-test_"], ["build/googletest/googletest-env-var-test_"], ["build/googletest/gtest_help_test_"], ["build/googletest/gtest_dll_test_"]]
# test_cmd_timeout = 7000
build_cmd = "./build.sh"
analyze_using_builtin = ["gtest"]
# stop executing tests as soon as a test command fails.
# This speed up the test phase but the report of test cases killing mutants is less accurate
use_early_stop = true
# reduce the compile+link time when testing mutants
use_schemata = true

# detected_new_test_case = "doNothing"|"resetAlive"
# how to behave when test cases are detected as having been removed
# should the test and the gathered statistics be remove too?
# detected_dropped_test_case = "remove"

[test_group]
[test_group.uc1]
description = "Parameterized Tests"
pattern = "Value.*|TypeTrait.*|Typed.*"
[test_group.uc2]
description = "Test Report"
pattern = "TestResult.*|TestPartResult.*|TestInfo.*"
[test_group.uc3]
description = "Resetting Mocks"
pattern = "VerifyAndClear.*"
