[workarea]
restrict = ["googlemock/include", "googlemock/src", "googletest/include", "googletest/src"]
[analyze]
exclude = ["googlemock/test", "googletest/test"]
[database]
db = "dextool_mutate.sqlite3"
[compiler]
extra_flags = [ "-D_POSIX_PATH_MAX=1024" ]
[compile_commands]
search_paths = ["./build/compile_commands.json"]
filter = ["-c", "-o", "-m", "-nodevicelib", "-Waddr-space-convert", "-non-static", "-Bstatic", "-Bdynamic", "-Xbind-lazy", "-Xbind-now", "-f", "-static", "-shared", "-rdynamic", "-s", "-l", "-L", "-z", "-u", "-T", "-Xlinker", "-l", "-MT", "-MF", "-MD", "-MQ", "-MMD", "-MP", "-MG", "-E", "-cc1", "-S", "-M", "-MM", "-###", "-Werror", "-Wunused-private-field"]
[mutant_test]
test_cmd = "test.sh"
# test_cmd_timeout = 7000
build_cmd = "build.sh"
analyze_using_builtin = ["gtest"]
# oldest_mutants = "test"
# oldest_mutants_nr = 2

# detected_new_test_case = "doNothing"|"resetAlive"
# how to behave when test cases are detected as having been removed
# should the test and the gathered statistics be remove too?
# detected_dropped_test_case = "remove"

[test_group]
[test_group.uc1]
description = "Parameterized Tests"
pattern = "Value.*|TypeTrait.*|Typed.*"
[test_group.uc2]
description = "Test Report"
pattern = "TestResult.*|TestPartResult.*|TestInfo.*"
[test_group.uc3]
description = "Resetting Mocks"
pattern = "VerifyAndClear.*"
